apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: basic-install
  namespace: knative-serving
spec:
  istio:
    global:
      mtls:
        enabled: false
      disablePolicyChecks: false
      policyCheckFailOpen: false
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 1Gi
    gateways:
      istio-egressgateway:
        autoscaleEnabled: true
      istio-ingressgateway:
        autoscaleEnabled: true
    mixer:
      policy:
        autoscaleEnabled: true
      telemetry:
        autoscaleEnabled: true
        resources:
          requests:
            cpu: 100m
            memory: 1G
          limits:
            cpu: 500m
            memory: 4G
    pilot:
      autoscaleEnabled: true
      traceSampling: 100
      resources:
          limits:
            cpu: 500m
            memory: 4Gi
    kiali:
      enabled: true
    grafana:
      enabled: true
    tracing:
      enabled: true
      jaeger:
        template: all-in-one