apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: quarkus-stack
  namespace: openshift
spec:
  tags:
  - annotations:
      description: Quarkus stack for Java and CodeReady Workspaces
      iconClass: icon-java
      supports: java
      tags: builder,java
      version: "1.3"
    from:
      kind: DockerImage
      name: quay.io/openshiftlabs/cloudnative-workspaces-quarkus:1.3
    name: "1.3"
